name: Generate Datas
on:
  schedule:
    - cron: "0 */6 * * *"  # Run every 6 hours
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Add this to ensure proper permissions
    
    steps:
      - uses: actions/checkout@v3  # Add checkout action
      
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: dharmikgohil
          svg_out_path: dist/github-contribution-grid-snake.svg
          
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
